from enum import StrEnum


class ProductionWorkflowStatus(StrEnum):
    DECISION_APPROVAL_VERIFIED = "DECISION_APPROVAL_VERIFIED"
    CONTENT_STRATEGY_RUNNING = "CONTENT_STRATEGY_RUNNING"
    CONTENT_STRATEGY_READY = "CONTENT_STRATEGY_READY"
    BRIEF_READY = "BRIEF_READY"
    PRODUCTION_RUNNING = "PRODUCTION_RUNNING"
    ASSET_VERSION_READY = "ASSET_VERSION_READY"
    ASSET_CONTROLLERS_RUNNING = "ASSET_CONTROLLERS_RUNNING"
    BLOCKED = "BLOCKED"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    PRODUCTION_READY = "PRODUCTION_READY"
    READY_FOR_ACTION_PROPOSAL = "READY_FOR_ACTION_PROPOSAL"
    ESCALATED = "ESCALATED"
