from enum import StrEnum


class EpistemicStatus(StrEnum):
    OBSERVATION = "OBSERVATION"
    FACT = "FACT"
    DERIVED_FACT = "DERIVED_FACT"
    HYPOTHESIS = "HYPOTHESIS"
    ASSUMPTION = "ASSUMPTION"
    UNKNOWN = "UNKNOWN"
    CONFLICT = "CONFLICT"
    REJECTED = "REJECTED"
    INVALIDATED = "INVALIDATED"


class VerificationBasis(StrEnum):
    DETERMINISTIC_SOURCE = "DETERMINISTIC_SOURCE"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    CALCULATION = "CALCULATION"
    MODEL_CONFIDENCE = "MODEL_CONFIDENCE"


class SourceTrust(StrEnum):
    UNTRUSTED_EXTERNAL = "UNTRUSTED_EXTERNAL"
    CONNECTOR = "CONNECTOR"
    USER_PROVIDED = "USER_PROVIDED"
    INTERNAL_SYSTEM = "INTERNAL_SYSTEM"


class CausalityClass(StrEnum):
    DIRECT_DETERMINISTIC_ATTRIBUTION = "DIRECT_DETERMINISTIC_ATTRIBUTION"
    EXPERIMENTAL_CAUSAL_EVIDENCE = "EXPERIMENTAL_CAUSAL_EVIDENCE"
    STRONG_OBSERVATIONAL_EVIDENCE = "STRONG_OBSERVATIONAL_EVIDENCE"
    CORRELATION = "CORRELATION"
    UNKNOWN = "UNKNOWN"


class BusinessOutcomeClass(StrEnum):
    QUALIFIED_INTENT = "QUALIFIED_INTENT"
    CTA_COMPLETION = "CTA_COMPLETION"
    LEAD = "LEAD"
    APPLICATION = "APPLICATION"
    BOOKING = "BOOKING"
    CHECKOUT = "CHECKOUT"
    PURCHASE_PAYMENT = "PURCHASE_PAYMENT"
    REFUND = "REFUND"
    RENEWAL = "RENEWAL"
    RETENTION = "RETENTION"
    REVENUE = "REVENUE"
    COST = "COST"
    CONTRIBUTION_MARGIN = "CONTRIBUTION_MARGIN"


class OutcomeInstrumentationStatus(StrEnum):
    DRAFT = "DRAFT"
    DISABLED_NON_LIVE = "DISABLED_NON_LIVE"
    RETIRED = "RETIRED"


class OutcomeMetricAggregation(StrEnum):
    COUNT = "COUNT"
    SUM = "SUM"
    RATE = "RATE"


class OutcomeDataAvailability(StrEnum):
    AVAILABLE = "AVAILABLE"
    PARTIAL = "PARTIAL"
    UNAVAILABLE = "UNAVAILABLE"
    STALE = "STALE"


class OutcomeEconomicLinkType(StrEnum):
    DIRECT_REVENUE = "DIRECT_REVENUE"
    CONTRIBUTION_MARGIN = "CONTRIBUTION_MARGIN"
    VALUE_PROXY = "VALUE_PROXY"
    HYPOTHETICAL_PROXY = "HYPOTHETICAL_PROXY"
    NONE = "NONE"


class DecisionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    INVALIDATED = "INVALIDATED"


class ControllerVerdict(StrEnum):
    PASS = "PASS"
    PASS_WITH_CONDITIONS = "PASS_WITH_CONDITIONS"
    REVISE = "REVISE"
    BLOCK = "BLOCK"


class LaunchPhaseStatus(StrEnum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    COMPLETE = "COMPLETE"
    PAUSED = "PAUSED"


class ExperimentStatus(StrEnum):
    DRAFT = "DRAFT"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    INVALIDATED = "INVALIDATED"


class PublicationStatus(StrEnum):
    DRAFT = "DRAFT"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    BLOCKED = "BLOCKED"


class PermissionMode(StrEnum):
    SUGGEST = "SUGGEST"
    PREPARE = "PREPARE"
    EXECUTE_AFTER_APPROVAL = "EXECUTE_AFTER_APPROVAL"
    LIMITED_AUTOPILOT = "LIMITED_AUTOPILOT"
    POLICY_AUTOPILOT = "POLICY_AUTOPILOT"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    INVALIDATED = "INVALIDATED"


class ActionStatus(StrEnum):
    PROPOSED = "PROPOSED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVED = "APPROVED"
    EXECUTED = "EXECUTED"
    BLOCKED = "BLOCKED"


class ExecutionStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    UNKNOWN_EXTERNAL_OUTCOME = "UNKNOWN_EXTERNAL_OUTCOME"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRY_WAIT = "RETRY_WAIT"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
